### PR TITLE
issue-259 Change animation of arrows in sources

### LINKED ISSUE #259: Change animation of arrows in sources
Bottom of https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1 (click on sources button).
Change animation of arrows in sources to be left to right fade-in.

### PR DESCRIPTION
**Pull request by allentsliu**
## Issue

Fix #259 

## 🔗 Test URLs:

- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
- After: https://issue-259--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1

### CODE REVIEW

**Comment by allentsliu** [comment]
@tmathern  the original page doesn't seem to have animation on the arrows. So, I removed the animation

**Review by tmathern — CHANGES_REQUESTED** [review]
THE ANIMATION NEEDS TO CHANGE TO A FADE-IN (DIFFERENT ANIMATION), NOT BE TOTALLY REMOVED

**Comment by allentsliu** [comment]
@tmathern  I made the change to use fade-in

**Comment by tmathern** [comment]
@allentsliu Is there a way you could also fade-in the background of the buttons?

**Review by tmathern — APPROVED** [review]

**Pull request merged**
