### PR TITLE
Product pages: decorative banners #107

### LINKED ISSUE #107: Product pages: decorative banners
Variant 1: Symetrical banners on left and right
2-borders-1
2-borders-2
2-borders-3

Variant 2: One long banner
1-border-1
1-border-2

Variant 3: One long banner with content overlap
1-border-overlap

### PR DESCRIPTION
**Pull request by atopper**
## Issue

Fix #107

## 🔗 Test URLs:

- Before: https://main--sgws-creative--hlxsites.hlx.page/drafts/top/decorban
- After: https://decor_banners107--sgws-creative--hlxsites.hlx.page/drafts/top/decorban
- After: https://decor_banners107--sgws-creative--hlxsites.hlx.page/drafts/top/decorban-1sheet
- After: https://decor_banners107--sgws-creative--hlxsites.hlx.page/drafts/top/decorban-1aztec

- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6
- After: https://decor_banners107--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6

One Image link: https://decor_banners107--sgws-creative--hlxsites.hlx.page/drafts/top/decorban-1image
Not a great image to use, but proves the concept - one image is `left: 0` and `width: 100vw;` (which makes it centered as well).

## 📝 Description:
Text with decorative banner, overlapping previous and next section
Trick here was really preparing the left & right images properly (from the source 4 separate images - flipping, stitching, etc.)

Also a quick fix for the vertical selector, and its default video size & showcase hotspots

### CODE REVIEW

**Comment by tmathern** [comment]
What about long single images banners like the one used in https://sgcreative.southernglazers.com/bloominbrands/p/3 ?

**Comment by atopper** [comment]
> What about long single image banners like the one used in https://sgcreative.southernglazers.com/bloominbrands/p/3 ?

If there is only 1 image, it'll be up against the left side and centered vertically.  The only difference will be the width of it.  I'll add another style indicating whether 1 or 2 images are specified - or could do it in script.

**Comment by tmathern** [comment]
> > What about long single image banners like the one used in https://sgcreative.southernglazers.com/bloominbrands/p/3 ?
> 
> If there is only 1 image, it'll be up against the left side and centered vertically. The only difference will be the width of it. I'll add another style indicating whether 1 or 2 images are specified - or could do it in script.

We should have the single image at least be in the middle, to give that "banner" impression.

**Review by tmathern — APPROVED** [review]
Try to start using a "real" product page as draft. It will help get correct LHS scoring.

**Pull request merged**
