### PR TITLE
Simi product page - fix footer style

### LINKED ISSUE #20: Author: Simi product page
https://sgcreative.southernglazers.com/bloominbrands/p/8

### PR DESCRIPTION
**Pull request by allentsliu**
## Issue

Fix 

## 🔗 Test URLs:

- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/8
- After: https://issue-20--sgws-creative--hlxsites.hlx.page/bloominbrands/p/8

## 📝 Description:

Screen Shot 2023-07-12 at 11 04 01 AM

### CODE REVIEW

**Comment by tmathern** [comment]
I fail to see the fix?

**Review by tmathern — CHANGES_REQUESTED** [review]
Both pages look identifcal to me.

**Comment by allentsliu** [comment]
This PR fixed the styling of the RETURN TO HOME background color in the footer

**Comment by atopper** [comment]
I see this using main.  The text is visible:
image

**Comment by atopper** [comment]
Had to look back and forth a few times, but I get it now. 👍

**Review by atopper — APPROVED** [review]

**Comment by allentsliu** [comment]
This is from the customer's page. Background color is wrong
Screen Shot 2023-07-12 at 11 46 33 AM

**Pull request closed without merging**
