### PR TITLE
Force divs to be wide enough for content

### LINKED ISSUE #132: Showcase popups are not wide enough
When a wider title ("FOOD PAIRING") was used, it exposed that the width did not contain the text.

See: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6

image

### PR DESCRIPTION
**Pull request by badvision**
## Issue

Fix #132

## 🔗 Test URLs:

- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6
- After: https://showcase-width--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6

## 📝 Description:
Added small CSS tweak

### CODE REVIEW

**Review by tmathern — CHANGES_REQUESTED** [review]
If you look at the fade-out animation, during the animation the width is off for food pairing. I think we need to fix the animation too...

**Comment by atopper** [comment]
@badvision I may have fixed the transition & width elsewhere, but only for the text that has been used.  Your fix might be better if SG uses other text.  Merge with master and check the transition.  Then I think this can be submitted.

**Review by atopper — APPROVED** [review]

**Comment by badvision** [comment]
> If you look at the fade-out animation, during the animation the width is off for food pairing. I think we need to fix the animation too...

I found the issue... I was setting width in :hover not the appropriate rule.  This is fixed now.

**Review by tmathern — APPROVED** [review]

**Comment by tmathern** [comment]
LGTM. Merging.

**Pull request merged**
