### PR TITLE
Add style to push down a background #152

### LINKED ISSUE #152: Add style to push down a background
For https://sgcreative.southernglazers.com/bloominbrands/p/5.

What we have:
Screenshot 2023-07-17 at 4 09 20 PM

What we want:
Screenshot 2023-07-17 at 4 10 42 PM

Add some padding somewhere so the background goes down, and the video gest mostly a white background.

### PR DESCRIPTION
**Pull request by atopper**
## Issue

Fix #152

## 🔗 Test URLs:

- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/5
- After: https://background-lower152--sgws-creative--hlxsites.hlx.page/bloominbrands/p/5

Another one: https://background-lower152--sgws-creative--hlxsites.hlx.page/bloominbrands/p/8

Original: https://sgcreative.southernglazers.com/bloominbrands/p/5

## 📝 Description:
The background originally used was not a background, but an image used as the last image before the real footer.
To make it work vertical padding & margins had to be remove from a few elements, so I added the style `no-vertical-padding`.  I also added `opacity-half` to make the image look like a background image (opacity: 0.5).

### CODE REVIEW

**Comment by tmathern** [comment]
It's needed for https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6 too (strangely it didn't seem to work there).

**Comment by tmathern** [comment]
So, the background image needs to be pushed down... So it needs to be a background image to start with. I think the `Highlight` style is missing in the authored content for the last image to get that (look closely - it's not taking the whole width):
Screenshot 2023-07-18 at 10 30 10 AM

**Review by tmathern — CHANGES_REQUESTED** [review]
THis seems to target an image, but we want to target a _background_ image.

**Comment by atopper** [comment]
`highlight` doesn't really work because there are no other elements to give the section any size - so the background image idea didn't really work easily.  I expand the `no-vertical-padding` style somehow.

**Review by tmathern — APPROVED** [review]

**Pull request merged**
