### PR TITLE
 Fix #181 by changing 'picture' element properties

### LINKED ISSUE #181: Landing page Portfolio: Background does not cover all portfolio
- Background does not cover all portfolio
- Background should not have opacity 50%
Screenshot 2023-07-24 at 10 26 38 AM

### PR DESCRIPTION
**Pull request by LeonardoLopesHonda**
## Issue

Fix #181 by changing 'picture' element properties (image is stretched with this change).

## 🔗 Test URLs:

- Before: https://main--sgws-creative--leonardolopeshonda.hlx.page
- After: https://issue-181--sgws-creative--leonardolopeshonda.hlx.page

### CODE REVIEW

**Review by tmathern — CHANGES_REQUESTED** [review]
This breaks other pages that need the opacity for the background to be 50%. 
See examples linked in https://github.com/hlxsites/sgws-creative/pull/223. 
One option to do so is to add a selector like `:not(product)` to the class restoring the opacity to 100% for the landing page.

**Comment by LeonardoLopesHonda** [comment]
> This breaks other pages that need the opacity for the background to be 50%. See examples linked in #223. One option to do so is to add a selector like `:not(product)` to the class restoring the opacity to 100% for the landing page.

Alright, I'll get another solution

**Comment by LeonardoLopesHonda** [comment]
I managed to get the same result by changing fewer lines. I just need to know if this will end up breaking some other page.

**Comment by LeonardoLopesHonda** [comment]
> This breaks other pages that need the opacity for the background to be 50%. See examples linked in #223. One option to do so is to add a selector like `:not(product)` to the class restoring the opacity to 100% for the landing page.

I've created another branch to solve the problem and use the link for comparison, will I need to make another pull request?

**Pull request closed without merging**
